name: Share data between jobs

on:
  push:
    branches: [main]

jobs:
  multiline-env:
    name: Multiline github env test
    runs-on: ubuntu-latest
    steps:
      # - name: Import credentials
      #   run: |
      #     echo "ENV_1=${{ secrets.ENV_1 }}" >> $GITHUB_ENV
      #     # echo "ENV_MULTILINE=${{ secrets.ENV_MULTILINE }}" >> $GITHUB_ENV
      - name: Linux import credentials
        run: |
          export ENV_1=${{ secrets.ENV_1 }}
      - name: Print credentials
        run: |
          echo $ENV_1
          echo $ENV_MULTILINE

